version: '3'
volumes:
        portainer_data:
services:
        jupyter-notebook:
                image: jupyter/minimal-notebook
                volumes: 
                                - ~/review/BDP2-midterm/work:/home/jovyan/work
                ports:
                        - 80:80

        portainer:
                image: portainer/portainer
                ports:
                        - 9000:9000
                volumes:
                        - portainer_data:/data/portainer
                #volumes:
                #        portainer_data:




        
