version: '3'
volumes:
        portainer_data:
services:
        jupyter-notebook:
                image: delaoliva17/bdp2-midterm:latest
                volumes: 
                        - ~/review/BDP2-midterm/work:/home/jovyan/work
                ports:
                        - 8888:8888

        portainer:
                image: portainer/portainer
                ports:
                        - 9000:9000
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock 
                        - portainer_data:/data/portainer/portainer 




        
